import { FoodItem, LeaderboardEntry, Notification, PickupRequest, Rating, SystemAnalytics, User, VolunteerOpportunity } from '../src/types';

export class DatabaseStore {
  public users: User[] = [];
  public foodItems: FoodItem[] = [];
  public pickups: PickupRequest[] = [];
  public notifications: Notification[] = [];
  public ratings: Rating[] = [];
  public volunteerOps: VolunteerOpportunity[] = [];

  constructor() {
    this.seed();
  }

  private seed() {
    // 1. Users
    this.users = [
      {
        id: 'user_rest_1',
        name: 'Chef Marco Rossi',
        email: 'marco@greenbites.com',
        role: 'restaurant',
        orgName: 'GreenBites Organic Bistro',
        orgType: 'Restaurant',
        address: '550 Market St, San Francisco, CA',
        phone: '+1 (415) 890-1234',
        lat: 37.7897,
        lng: -122.4012,
        verified: true,
        avatarUrl: 'https://images.unsplash.com/photo-1577219491135-ce391730fb2c?auto=format&fit=crop&w=200&q=80',
        rating: 4.9,
        totalDonations: 42,
        mealsSaved: 1250,
        impactBadge: 'Zero Waste Pioneer',
        createdAt: '2026-01-15T08:00:00Z'
      },
      {
        id: 'user_rest_2',
        name: 'Elena Rostova',
        email: 'elena@grandhyattsf.com',
        role: 'restaurant',
        orgName: 'Grand Hyatt Executive Dining',
        orgType: 'Hotel',
        address: '345 Stockton St, San Francisco, CA',
        phone: '+1 (415) 398-1234',
        lat: 37.7891,
        lng: -122.4068,
        verified: true,
        avatarUrl: 'https://images.unsplash.com/photo-1566554273541-37a9ca77b91f?auto=format&fit=crop&w=200&q=80',
        rating: 4.8,
        totalDonations: 88,
        mealsSaved: 3400,
        impactBadge: 'Community Shield',
        createdAt: '2026-02-01T08:00:00Z'
      },
      {
        id: 'user_rest_3',
        name: 'Pierre Laurent',
        email: 'pierre@artisanbakery.com',
        role: 'restaurant',
        orgName: 'Golden Gate Artisan Bakery',
        orgType: 'Bakery',
        address: '1020 Valencia St, San Francisco, CA',
        phone: '+1 (415) 641-5522',
        lat: 37.7554,
        lng: -122.4211,
        verified: true,
        avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
        rating: 4.95,
        totalDonations: 65,
        mealsSaved: 1980,
        impactBadge: 'Golden Baker',
        createdAt: '2026-02-10T08:00:00Z'
      },
      {
        id: 'user_ngo_1',
        name: 'Sarah Jenkins',
        email: 'sarah@hopekitchen.org',
        role: 'ngo',
        orgName: 'Hope Community Kitchen',
        orgType: 'Food Bank',
        address: '888 Howard St, San Francisco, CA',
        phone: '+1 (415) 555-0199',
        lat: 37.7825,
        lng: -122.4042,
        verified: true,
        avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
        rating: 5.0,
        totalDonations: 120,
        mealsSaved: 4800,
        impactBadge: 'Master Distributor',
        createdAt: '2026-01-10T08:00:00Z'
      },
      {
        id: 'user_ngo_2',
        name: 'David Chen',
        email: 'david@bayareaharvest.org',
        role: 'ngo',
        orgName: 'Bay Area Harvest Network',
        orgType: 'NGO',
        address: '1450 Mission St, San Francisco, CA',
        phone: '+1 (415) 555-0288',
        lat: 37.7738,
        lng: -122.4178,
        verified: true,
        avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
        rating: 4.9,
        totalDonations: 95,
        mealsSaved: 3800,
        impactBadge: 'Rapid Dispatch',
        createdAt: '2026-01-20T08:00:00Z'
      },
      {
        id: 'user_admin_1',
        name: 'Admin Director',
        email: 'admin@foodlink.ai',
        role: 'admin',
        orgName: 'FoodLink Global Operations',
        orgType: 'Admin Headquarters',
        address: '100 Pine St, San Francisco, CA',
        phone: '+1 (415) 500-9000',
        lat: 37.7925,
        lng: -122.3995,
        verified: true,
        avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80',
        createdAt: '2026-01-01T08:00:00Z'
      }
    ];

    // Helper for relative timestamps
    const now = new Date();
    const plusHours = (h: number) => new Date(now.getTime() + h * 60 * 60 * 1000).toISOString();
    const minusHours = (h: number) => new Date(now.getTime() - h * 60 * 60 * 1000).toISOString();

    // 2. Food Items - Worldwide Surplus Listings
    this.foodItems = [
      {
        id: 'food_101',
        restaurantId: 'user_rest_1',
        restaurantName: 'GreenBites Organic Bistro',
        restaurantAddress: '550 Market St, San Francisco, CA',
        city: 'San Francisco',
        country: 'United States',
        region: 'North America',
        lat: 37.7897,
        lng: -122.4012,
        foodName: 'Gourmet Mediterranean Quinoa Bowls',
        category: 'Cooked Meals',
        quantity: 25,
        quantityUnit: 'portions',
        preparedAt: minusHours(2),
        expiryTime: plusHours(3.5),
        pickupWindowStart: minusHours(0.5),
        pickupWindowEnd: plusHours(3),
        foodCondition: 'Freshly Prepared',
        imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=600&q=80',
        status: 'Safe',
        urgencyScore: 78,
        freshnessConfidence: 96.8,
        predictedFreshnessState: 'Safe',
        dietaryInfo: ['Vegetarian', 'Gluten-Free', 'Organic'],
        storageCondition: 'Refrigerated',
        notes: 'Packaged in eco-friendly biodegradable containers. Includes roast veggies and hummus.',
        isReserved: false,
        qrCodeData: 'FLK-QR-MED-101-2026',
        createdAt: minusHours(2)
      },
      {
        id: 'food_102',
        restaurantId: 'user_rest_2',
        restaurantName: 'Grand Hyatt Executive Dining',
        restaurantAddress: '345 Stockton St, San Francisco, CA',
        city: 'San Francisco',
        country: 'United States',
        region: 'North America',
        lat: 37.7891,
        lng: -122.4068,
        foodName: 'Banquet Buffet Trays: Grilled Chicken & Wild Rice',
        category: 'Cooked Meals',
        quantity: 40,
        quantityUnit: 'kg',
        preparedAt: minusHours(3),
        expiryTime: plusHours(1.8),
        pickupWindowStart: minusHours(1),
        pickupWindowEnd: plusHours(1.5),
        foodCondition: 'Requires Reheating',
        imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=600&q=80',
        status: 'Urgent Pickup',
        urgencyScore: 92,
        freshnessConfidence: 94.2,
        predictedFreshnessState: 'Consume Soon',
        dietaryInfo: ['High Protein', 'Halal Compliant'],
        storageCondition: 'Refrigerated',
        notes: 'Hot buffet trays sealed under insulated covers. Ready for thermal transport.',
        isReserved: true,
        reservedByNgoId: 'user_ngo_1',
        reservedByNgoName: 'Hope Community Kitchen',
        qrCodeData: 'FLK-QR-HYATT-102-2026',
        createdAt: minusHours(3)
      },
      {
        id: 'food_103',
        restaurantId: 'user_rest_3',
        restaurantName: 'Golden Gate Artisan Bakery',
        restaurantAddress: '1020 Valencia St, San Francisco, CA',
        city: 'San Francisco',
        country: 'United States',
        region: 'North America',
        lat: 37.7554,
        lng: -122.4211,
        foodName: 'Assorted Sourdough Loaves & French Croissants',
        category: 'Bakery & Bread',
        quantity: 35,
        quantityUnit: 'boxes',
        preparedAt: minusHours(5),
        expiryTime: plusHours(18),
        pickupWindowStart: minusHours(1),
        pickupWindowEnd: plusHours(12),
        foodCondition: 'Good',
        imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
        status: 'Safe',
        urgencyScore: 45,
        freshnessConfidence: 98.1,
        predictedFreshnessState: 'Safe',
        dietaryInfo: ['Vegetarian', 'Artisanal'],
        storageCondition: 'Ambient',
        notes: 'Baked fresh this morning. Wrapped in parchment paper.',
        isReserved: false,
        qrCodeData: 'FLK-QR-BAKERY-103-2026',
        createdAt: minusHours(5)
      },
      {
        id: 'food_104',
        restaurantId: 'user_rest_1',
        restaurantName: 'GreenBites Organic Bistro',
        restaurantAddress: '550 Market St, San Francisco, CA',
        city: 'San Francisco',
        country: 'United States',
        region: 'North America',
        lat: 37.7897,
        lng: -122.4012,
        foodName: 'Organic Fruit Crates: Apples, Berries & Oranges',
        category: 'Fresh Produce',
        quantity: 20,
        quantityUnit: 'kg',
        preparedAt: minusHours(6),
        expiryTime: plusHours(24),
        pickupWindowStart: minusHours(2),
        pickupWindowEnd: plusHours(16),
        foodCondition: 'Good',
        imageUrl: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&w=600&q=80',
        status: 'Safe',
        urgencyScore: 35,
        freshnessConfidence: 99.0,
        predictedFreshnessState: 'Safe',
        dietaryInfo: ['Raw', 'Vegan', 'Organic'],
        storageCondition: 'Ambient',
        notes: 'Slightly imperfect aesthetic produce, perfectly crisp and wholesome.',
        isReserved: false,
        qrCodeData: 'FLK-QR-PRODUCE-104-2026',
        createdAt: minusHours(6)
      },
      {
        id: 'food_201',
        restaurantId: 'user_rest_tokyo',
        restaurantName: 'Roppongi Grand Dining & Bento',
        restaurantAddress: '6-10-1 Roppongi, Minato-ku, Tokyo',
        city: 'Tokyo',
        country: 'Japan',
        region: 'Asia Pacific',
        lat: 35.6628,
        lng: 139.7314,
        foodName: 'Deluxe Bento Meal Trays & Vegetable Tempura',
        category: 'Cooked Meals',
        quantity: 50,
        quantityUnit: 'portions',
        preparedAt: minusHours(1.5),
        expiryTime: plusHours(4),
        pickupWindowStart: minusHours(0.5),
        pickupWindowEnd: plusHours(3.5),
        foodCondition: 'Freshly Prepared',
        imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=600&q=80',
        status: 'Safe',
        urgencyScore: 82,
        freshnessConfidence: 98.5,
        predictedFreshnessState: 'Safe',
        dietaryInfo: ['Seafood', 'Halal Option', 'High Protein'],
        storageCondition: 'Refrigerated',
        notes: 'Chef crafted Bento trays with teriyaki salmon, rice, and edamame.',
        isReserved: false,
        qrCodeData: 'FLK-QR-TOKYO-201-2026',
        createdAt: minusHours(1.5)
      },
      {
        id: 'food_202',
        restaurantId: 'user_rest_london',
        restaurantName: 'Covent Garden Artisan Bakery',
        restaurantAddress: '14 Floral St, London WC2E 9DH',
        city: 'London',
        country: 'United Kingdom',
        region: 'Europe',
        lat: 51.5117,
        lng: -0.1240,
        foodName: 'Artisan English Scones, Tartlets & Sourdough',
        category: 'Bakery & Bread',
        quantity: 30,
        quantityUnit: 'boxes',
        preparedAt: minusHours(3),
        expiryTime: plusHours(14),
        pickupWindowStart: minusHours(1),
        pickupWindowEnd: plusHours(10),
        foodCondition: 'Good',
        imageUrl: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=600&q=80',
        status: 'Safe',
        urgencyScore: 50,
        freshnessConfidence: 97.2,
        predictedFreshnessState: 'Safe',
        dietaryInfo: ['Vegetarian', 'Nut-Free'],
        storageCondition: 'Ambient',
        notes: 'Baked fresh in central London. Packed with clotted cream tarts and breads.',
        isReserved: false,
        qrCodeData: 'FLK-QR-LONDON-202-2026',
        createdAt: minusHours(3)
      },
      {
        id: 'food_203',
        restaurantId: 'user_rest_paris',
        restaurantName: 'Boulangerie Eiffel & Delicatessen',
        restaurantAddress: '18 Avenue de la Motte-Picquet, Paris',
        city: 'Paris',
        country: 'France',
        region: 'Europe',
        lat: 48.8584,
        lng: 2.2945,
        foodName: 'French Quiches, Organic Baguettes & Cheese Trays',
        category: 'Cooked Meals',
        quantity: 45,
        quantityUnit: 'portions',
        preparedAt: minusHours(2),
        expiryTime: plusHours(5),
        pickupWindowStart: minusHours(0.5),
        pickupWindowEnd: plusHours(4),
        foodCondition: 'Freshly Prepared',
        imageUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=600&q=80',
        status: 'Safe',
        urgencyScore: 75,
        freshnessConfidence: 96.9,
        predictedFreshnessState: 'Safe',
        dietaryInfo: ['Vegetarian', 'Artisanal Cheese'],
        storageCondition: 'Refrigerated',
        notes: 'Traditional Parisian spinach & brie quiches ready for shelter distribution.',
        isReserved: false,
        qrCodeData: 'FLK-QR-PARIS-203-2026',
        createdAt: minusHours(2)
      },
      {
        id: 'food_204',
        restaurantId: 'user_rest_mumbai',
        restaurantName: 'Taj Spice Heritage & Caterers',
        restaurantAddress: 'Apollo Bunder, Colaba, Mumbai',
        city: 'Mumbai',
        country: 'India',
        region: 'Asia Pacific',
        lat: 19.0760,
        lng: 72.8777,
        foodName: 'Royal Veg Biryani & Paneer Butter Masala Trays',
        category: 'Cooked Meals',
        quantity: 80,
        quantityUnit: 'portions',
        preparedAt: minusHours(1.8),
        expiryTime: plusHours(3),
        pickupWindowStart: minusHours(0.5),
        pickupWindowEnd: plusHours(2.5),
        foodCondition: 'Freshly Prepared',
        imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80',
        status: 'Urgent Pickup',
        urgencyScore: 89,
        freshnessConfidence: 95.8,
        predictedFreshnessState: 'Consume Soon',
        dietaryInfo: ['Pure Vegetarian', 'Halal', 'Spiced'],
        storageCondition: 'Refrigerated',
        notes: 'Hot buffet trays prepared for executive banquet in Mumbai. High nutrition.',
        isReserved: false,
        qrCodeData: 'FLK-QR-MUMBAI-204-2026',
        createdAt: minusHours(1.8)
      },
      {
        id: 'food_205',
        restaurantId: 'user_rest_ny',
        restaurantName: 'Manhattan Harbor Seafood & Grill',
        restaurantAddress: '230 Vesey St, New York, NY',
        city: 'New York',
        country: 'United States',
        region: 'North America',
        lat: 40.7128,
        lng: -74.0060,
        foodName: 'Pan-Roasted Atlantic Salmon & Wild Rice Platters',
        category: 'Cooked Meals',
        quantity: 30,
        quantityUnit: 'kg',
        preparedAt: minusHours(2.5),
        expiryTime: plusHours(2.8),
        pickupWindowStart: minusHours(0.5),
        pickupWindowEnd: plusHours(2),
        foodCondition: 'Freshly Prepared',
        imageUrl: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80',
        status: 'Safe',
        urgencyScore: 80,
        freshnessConfidence: 96.1,
        predictedFreshnessState: 'Safe',
        dietaryInfo: ['Seafood', 'Gluten-Free', 'Omega-Rich'],
        storageCondition: 'Refrigerated',
        notes: 'Plated salmon cuts with roasted asparagus and lemon herb dressing.',
        isReserved: false,
        qrCodeData: 'FLK-QR-NY-205-2026',
        createdAt: minusHours(2.5)
      },
      {
        id: 'food_206',
        restaurantId: 'user_rest_sydney',
        restaurantName: 'Sydney Opera Harbour Kitchen',
        restaurantAddress: 'Bennelong Point, Sydney NSW',
        city: 'Sydney',
        country: 'Australia',
        region: 'Asia Pacific',
        lat: -33.8568,
        lng: 151.2153,
        foodName: 'Fresh Avocado Grain Bowls & Flatbread Salads',
        category: 'Fresh Produce',
        quantity: 40,
        quantityUnit: 'portions',
        preparedAt: minusHours(1),
        expiryTime: plusHours(6),
        pickupWindowStart: minusHours(0.2),
        pickupWindowEnd: plusHours(5),
        foodCondition: 'Freshly Prepared',
        imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80',
        status: 'Safe',
        urgencyScore: 60,
        freshnessConfidence: 99.1,
        predictedFreshnessState: 'Safe',
        dietaryInfo: ['Vegan', 'Organic', 'Plant-Based'],
        storageCondition: 'Refrigerated',
        notes: 'Chilled organic grain bowls prepared for Australian harbor event.',
        isReserved: false,
        qrCodeData: 'FLK-QR-SYDNEY-206-2026',
        createdAt: minusHours(1)
      },
      {
        id: 'food_207',
        restaurantId: 'user_rest_saopaulo',
        restaurantName: 'Paulista Churrascaria & Buffet',
        restaurantAddress: 'Av. Paulista 1000, São Paulo',
        city: 'São Paulo',
        country: 'Brazil',
        region: 'Latin America',
        lat: -23.5505,
        lng: -46.6333,
        foodName: 'Churrasco Roasted Vegetables & Feijoada Pans',
        category: 'Cooked Meals',
        quantity: 60,
        quantityUnit: 'kg',
        preparedAt: minusHours(2.2),
        expiryTime: plusHours(3.2),
        pickupWindowStart: minusHours(0.5),
        pickupWindowEnd: plusHours(2.5),
        foodCondition: 'Requires Reheating',
        imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80',
        status: 'Safe',
        urgencyScore: 79,
        freshnessConfidence: 95.4,
        predictedFreshnessState: 'Safe',
        dietaryInfo: ['Traditional Brazilian', 'High Energy'],
        storageCondition: 'Refrigerated',
        notes: 'Rich black bean stew and charbroiled veggies packed in bulk pans.',
        isReserved: false,
        qrCodeData: 'FLK-QR-SAOPAULO-207-2026',
        createdAt: minusHours(2.2)
      },
      {
        id: 'food_208',
        restaurantId: 'user_rest_dubai',
        restaurantName: 'Emirates Grand Hospitality',
        restaurantAddress: 'Sheikh Zayed Rd, Dubai',
        city: 'Dubai',
        country: 'United Arab Emirates',
        region: 'Middle East & Africa',
        lat: 25.2048,
        lng: 55.2708,
        foodName: 'Halal Roast Lamb, Hummus & Fresh Date Trays',
        category: 'Cooked Meals',
        quantity: 70,
        quantityUnit: 'portions',
        preparedAt: minusHours(1.2),
        expiryTime: plusHours(4.5),
        pickupWindowStart: minusHours(0.3),
        pickupWindowEnd: plusHours(4),
        foodCondition: 'Freshly Prepared',
        imageUrl: 'https://images.unsplash.com/photo-1541518763669-27fef04b14ea?auto=format&fit=crop&w=600&q=80',
        status: 'Safe',
        urgencyScore: 70,
        freshnessConfidence: 98.9,
        predictedFreshnessState: 'Safe',
        dietaryInfo: ['100% Halal', 'Gourmet', 'Dairy-Free'],
        storageCondition: 'Refrigerated',
        notes: 'Exquisite Arabian hospitality surplus packed for community distribution.',
        isReserved: false,
        qrCodeData: 'FLK-QR-DUBAI-208-2026',
        createdAt: minusHours(1.2)
      }
    ];

    // 3. Pickups
    this.pickups = [
      {
        id: 'pick_201',
        foodItemId: 'food_102',
        foodName: 'Banquet Buffet Trays: Grilled Chicken & Wild Rice',
        quantity: 40,
        quantityUnit: 'kg',
        restaurantId: 'user_rest_2',
        restaurantName: 'Grand Hyatt Executive Dining',
        restaurantAddress: '345 Stockton St, San Francisco, CA',
        restaurantLat: 37.7891,
        restaurantLng: -122.4068,
        ngoId: 'user_ngo_1',
        ngoName: 'Hope Community Kitchen',
        ngoAddress: '888 Howard St, San Francisco, CA',
        ngoLat: 37.7825,
        ngoLng: -122.4042,
        status: 'In Transit',
        trackingNumber: 'LOG-FLK-882910',
        courierName: 'Carlos Ramirez (Eco Van #4)',
        courierPhone: '+1 (415) 992-8811',
        estimatedArrivalMinutes: 12,
        scheduledTime: minusHours(0.5),
        qrVerificationCode: '8829-FLK-VERIFY',
        verifiedByNgo: false,
        logisticsProvider: 'FoodLink Express Fleet'
      }
    ];

    // 4. Notifications
    this.notifications = [
      {
        id: 'notif_1',
        userId: 'user_ngo_1',
        title: '🔥 Urgent Donation Nearby!',
        message: 'Grand Hyatt listed 40 kg of Banquet Buffet Trays expiring in under 2 hours.',
        type: 'urgency',
        read: false,
        timestamp: minusHours(1),
        linkId: 'food_102'
      },
      {
        id: 'notif_2',
        userId: 'user_rest_2',
        title: '✅ Pickup Scheduled',
        message: 'Hope Community Kitchen accepted your donation. Courier Carlos Ramirez is en route.',
        type: 'pickup',
        read: true,
        timestamp: minusHours(0.5),
        linkId: 'pick_201'
      }
    ];

    // 5. Ratings
    this.ratings = [
      {
        id: 'rate_1',
        fromUserId: 'user_ngo_1',
        fromUserName: 'Hope Community Kitchen',
        toUserId: 'user_rest_1',
        foodItemId: 'food_101',
        stars: 5,
        comment: 'Pristine packaging and hot gourmet meals! Our community shelter residents loved the quinoa bowls.',
        createdAt: minusHours(24)
      }
    ];

    // 6. Volunteer Opportunities
    this.volunteerOps = [
      {
        id: 'vol_1',
        title: 'Evening Surplus Food Driver',
        ngoName: 'Hope Community Kitchen',
        location: 'Downtown San Francisco Route',
        date: 'Today, July 24',
        timeSlot: '6:00 PM - 8:30 PM',
        roleType: 'Food Driver',
        spotsLeft: 3,
        description: 'Drive insulated electric van to pick up hot meals from partner hotels and deliver to shelter.'
      },
      {
        id: 'vol_2',
        title: 'Bakery & Fresh Produce Sorting Specialist',
        ngoName: 'Bay Area Harvest Network',
        location: '1450 Mission St Warehouse',
        date: 'Tomorrow, July 25',
        timeSlot: '9:00 AM - 12:00 PM',
        roleType: 'Sorting & Quality Check',
        spotsLeft: 5,
        description: 'Inspect sourdough loaves, package artisan pastries, and categorize produce crate deliveries.'
      },
      {
        id: 'vol_3',
        title: 'Community Meal Distribution Captain',
        ngoName: 'St. Vincent Food Bank',
        location: 'SoMa Meal Hall',
        date: 'Saturday, July 26',
        timeSlot: '11:00 AM - 2:00 PM',
        roleType: 'Meal Distribution',
        spotsLeft: 2,
        description: 'Assist in hot meal tray distribution, greeting visitors, and maintaining hygiene standards.'
      }
    ];
  }

  // Database helper methods
  public getAnalytics(): SystemAnalytics {
    const totalDonationsKg = this.foodItems.reduce((acc, item) => acc + item.quantity, 1480);
    const totalMealsSaved = Math.round(totalDonationsKg * 2.2);
    const co2SavedKg = Math.round(totalDonationsKg * 2.5);
    const waterSavedLiters = Math.round(totalDonationsKg * 950);

    return {
      totalDonationsKg,
      totalMealsSaved,
      co2SavedKg,
      waterSavedLiters,
      activeRestaurantsCount: this.users.filter((u) => u.role === 'restaurant').length,
      activeNgosCount: this.users.filter((u) => u.role === 'ngo').length,
      completedPickups: 154,
      pendingPickups: this.pickups.filter((p) => p.status !== 'Completed').length,
      freshnessAccuracyPercentage: 97.4,
      monthlyTrends: [
        { month: 'Jan', kgDonated: 850, mealsSaved: 1870 },
        { month: 'Feb', kgDonated: 1100, mealsSaved: 2420 },
        { month: 'Mar', kgDonated: 1250, mealsSaved: 2750 },
        { month: 'Apr', kgDonated: 1400, mealsSaved: 3080 },
        { month: 'May', kgDonated: 1650, mealsSaved: 3630 },
        { month: 'Jun', kgDonated: 1800, mealsSaved: 3960 },
        { month: 'Jul', kgDonated: 2100, mealsSaved: 4620 }
      ],
      categoryBreakdown: [
        { category: 'Cooked Meals', percentage: 42 },
        { category: 'Bakery & Bread', percentage: 28 },
        { category: 'Fresh Produce', percentage: 18 },
        { category: 'Dairy & Packaged', percentage: 12 }
      ]
    };
  }

  public getLeaderboard(): LeaderboardEntry[] {
    return [
      { rank: 1, name: 'Grand Hyatt Executive Dining', type: 'Restaurant', totalKgSaved: 3400, mealsServed: 7480, badge: 'Titan Donor', verified: true },
      { rank: 2, name: 'Golden Gate Artisan Bakery', type: 'Restaurant', totalKgSaved: 1980, mealsServed: 4356, badge: 'Golden Baker', verified: true },
      { rank: 3, name: 'GreenBites Organic Bistro', type: 'Restaurant', totalKgSaved: 1250, mealsServed: 2750, badge: 'Zero Waste Pioneer', verified: true },
      { rank: 4, name: 'Bay Area Caterers Guild', type: 'Restaurant', totalKgSaved: 920, mealsServed: 2024, badge: 'Community Hero', verified: true },
      { rank: 5, name: 'FreshMarket Grocery', type: 'Restaurant', totalKgSaved: 840, mealsServed: 1848, badge: 'Green Retailer', verified: true }
    ];
  }
}

export const db = new DatabaseStore();
